# Generates SEO alt texts + per-language meta (appended to i18n.js as i18n-seo.js block)
import json

LANGS = ['en', 'fa', 'ar', 'ru', 'es', 'it', 'zh', 'ja', 'de', 'fr']

T = {
'en': dict(
  metaTitle='Interior Designer & Decorator in Dubai | Farnaz Sadeghian',
  metaDesc='Certified interior decorator in Dubai. Interior design consultation, 3D room design and home styling for apartments and villas by Farnaz Sadeghian.',
  metaKeywords='interior designer Dubai, interior decorator Dubai, interior design consultation Dubai, home styling Dubai, apartment interior design Dubai, villa interior design Dubai, 3D interior design Dubai, Persian interior designer Dubai, Farnaz Sadeghian, Decor with Farnaz, Third Skin Interiors',
  altHeroImg='Farnaz Sadeghian, certified interior decorator in Dubai',
  wallart='Gallery wall with framed art above a sofa – home decor idea',
  corner='Styled living room corner with armchair and lamp',
  bathroom='Bathroom interior design with warm neutral finishes',
  colour='Colour palette idea for a calm living room',
  pillar='Decorated column in an open-plan apartment in Dubai',
  console='Entryway console table styled with decor accessories',
  accessories='Home accessories styling: vases, books and candles',
  baA='{r} after interior styling by Farnaz Sadeghian – Dubai apartment makeover',
  baB='{r} before interior styling – Dubai apartment',
  topic='{t} – interior design tip by Farnaz Sadeghian',
  reel='{t} – interior decor reel by Decor with Farnaz',
  book='Soul of the Room, interior design book by Farnaz Sadeghian'),
'fa': dict(
  metaTitle='دکوراسیون داخلی و چیدمان خانه · فرناز صادقیان | طراح داخلی در دبی',
  metaDesc='ایده‌های دکوراسیون داخلی و چیدمان خانه از فرناز صادقیان، دکوراتور داخلی دارای مدرک در دبی با ۳۹۰ هزار دنبال‌کننده. مشاوره‌ی طراحی داخلی، طراحی سه‌بعدی و چیدمان آپارتمان و ویلا.',
  metaKeywords='دکوراسیون داخلی, چیدمان خانه, چیدمان منزل, ایده دکوراسیون, طراحی داخلی, مشاوره دکوراسیون داخلی, دکوراسیون خانه کوچک, طراح داخلی ایرانی در دبی, طراحی سه بعدی داخلی, فرناز صادقیان, دکور با فرناز',
  altHeroImg='فرناز صادقیان، دکوراتور و طراح داخلی در دبی',
  wallart='دیوار گالری با تابلوهای قاب‌شده بالای کاناپه – ایده دکوراسیون خانه',
  corner='گوشه‌ی چیده‌شده‌ی نشیمن با مبل تک و آباژور',
  bathroom='طراحی داخلی حمام با رنگ‌های گرم و خنثی',
  colour='ایده‌ی ترکیب رنگ برای پذیرایی آرام',
  pillar='ستون دکور شده در آپارتمان با فضای باز',
  console='کنسول ورودی چیده‌شده با اکسسوری‌های دکوری',
  accessories='چیدمان اکسسوری خانه: گلدان، کتاب و شمع',
  baA='{r} بعد از چیدمان و دکوراسیون توسط فرناز صادقیان',
  baB='{r} قبل از چیدمان و دکوراسیون',
  topic='{t} – نکته‌ی دکوراسیون داخلی از فرناز صادقیان',
  reel='{t} – ریلز دکوراسیون داخلی دکور با فرناز',
  book='کتاب «روح اتاق» درباره‌ی دکوراسیون داخلی، نوشته‌ی فرناز صادقیان'),
'ar': dict(
  metaTitle='مصممة ديكور داخلي في دبي · فرناز صادقيان | Third Skin Interiors',
  metaDesc='مصممة ومنسّقة ديكور داخلي معتمدة في دبي. استشارات تصميم داخلي وتصميم ثلاثي الأبعاد وتنسيق ديكور الشقق والفلل، من فرناز صادقيان صاحبة 390 ألف متابع.',
  metaKeywords='تصميم داخلي دبي, مصممة ديكور دبي, ديكور شقق دبي, تصميم فلل دبي, استشارة تصميم داخلي, تصميم ثلاثي الأبعاد, تنسيق ديكور المنزل, فرناز صادقيان',
  altHeroImg='فرناز صادقيان، مصممة ديكور داخلي معتمدة في دبي',
  wallart='جدار معرض بلوحات مؤطرة فوق الكنبة – فكرة ديكور منزلي',
  corner='زاوية جلوس منسّقة بكرسي ومصباح',
  bathroom='تصميم داخلي لحمام بألوان دافئة محايدة',
  colour='فكرة لوحة ألوان لغرفة معيشة هادئة',
  pillar='عمود مزيّن في شقة مفتوحة في دبي',
  console='طاولة مدخل منسّقة بإكسسوارات الديكور',
  accessories='تنسيق إكسسوارات المنزل: مزهريات وكتب وشموع',
  baA='{r} بعد تنسيق الديكور من فرناز صادقيان – شقة في دبي',
  baB='{r} قبل تنسيق الديكور – شقة في دبي',
  topic='{t} – نصيحة تصميم داخلي من فرناز صادقيان',
  reel='{t} – ريلز ديكور من Decor with Farnaz',
  book='كتاب «روح الغرفة» عن التصميم الداخلي لفرناز صادقيان'),
'ru': dict(
  metaTitle='Дизайнер интерьера в Дубае · Фарназ Садегиан | Third Skin Interiors',
  metaDesc='Сертифицированный декоратор интерьера в Дубае. Консультации по дизайну интерьера, 3D-дизайн и стилизация квартир и вилл от Фарназ Садегиан (390 тыс. подписчиков).',
  metaKeywords='дизайнер интерьера Дубай, дизайн интерьера Дубай, декоратор Дубай, дизайн квартиры Дубай, дизайн виллы Дубай, 3D дизайн интерьера, Фарназ Садегиан',
  altHeroImg='Фарназ Садегиан, сертифицированный декоратор интерьера в Дубае',
  wallart='Галерейная стена с картинами над диваном – идея декора',
  corner='Оформленный уголок гостиной с креслом и лампой',
  bathroom='Дизайн ванной комнаты в тёплых нейтральных тонах',
  colour='Идея цветовой палитры для спокойной гостиной',
  pillar='Декорированная колонна в квартире открытой планировки в Дубае',
  console='Консоль в прихожей с декором',
  accessories='Стилизация аксессуаров: вазы, книги и свечи',
  baA='{r} после стилизации интерьера от Фарназ Садегиан – квартира в Дубае',
  baB='{r} до стилизации интерьера – квартира в Дубае',
  topic='{t} – совет по дизайну интерьера от Фарназ Садегиан',
  reel='{t} – рилс о декоре от Decor with Farnaz',
  book='Книга о дизайне интерьера «Soul of the Room» Фарназ Садегиан'),
'es': dict(
  metaTitle='Diseñadora de interiores en Dubái · Farnaz Sadeghian | Third Skin Interiors',
  metaDesc='Decoradora de interiores certificada en Dubái. Consultoría de interiorismo, diseño 3D y estilismo de pisos y villas, de Farnaz Sadeghian (390K seguidores).',
  metaKeywords='diseñadora de interiores Dubái, interiorismo Dubái, decoradora Dubái, diseño 3D de interiores, decoración de pisos Dubái, Farnaz Sadeghian',
  altHeroImg='Farnaz Sadeghian, decoradora de interiores certificada en Dubái',
  wallart='Pared de galería con cuadros enmarcados sobre el sofá – idea de decoración',
  corner='Rincón de salón decorado con butaca y lámpara',
  bathroom='Diseño de baño con acabados neutros y cálidos',
  colour='Idea de paleta de colores para un salón tranquilo',
  pillar='Columna decorada en un piso de planta abierta en Dubái',
  console='Consola de entrada decorada con accesorios',
  accessories='Estilismo de accesorios: jarrones, libros y velas',
  baA='{r} después del estilismo de Farnaz Sadeghian – piso en Dubái',
  baB='{r} antes del estilismo – piso en Dubái',
  topic='{t} – consejo de interiorismo de Farnaz Sadeghian',
  reel='{t} – reel de decoración de Decor with Farnaz',
  book='Soul of the Room, libro de interiorismo de Farnaz Sadeghian'),
'it': dict(
  metaTitle='Interior designer a Dubai · Farnaz Sadeghian | Third Skin Interiors',
  metaDesc='Interior decorator certificata a Dubai. Consulenza di interior design, progettazione 3D e styling di appartamenti e ville, di Farnaz Sadeghian (390K follower).',
  metaKeywords='interior designer Dubai, arredatrice Dubai, consulenza interior design, progettazione 3D interni, arredamento appartamento Dubai, Farnaz Sadeghian',
  altHeroImg='Farnaz Sadeghian, interior decorator certificata a Dubai',
  wallart='Parete galleria con quadri incorniciati sopra il divano – idea d’arredo',
  corner='Angolo del soggiorno arredato con poltrona e lampada',
  bathroom='Interior design del bagno con finiture neutre e calde',
  colour='Idea di palette colori per un soggiorno rilassante',
  pillar='Colonna decorata in un appartamento open space a Dubai',
  console='Consolle d’ingresso decorata con accessori',
  accessories='Styling degli accessori: vasi, libri e candele',
  baA='{r} dopo lo styling di Farnaz Sadeghian – appartamento a Dubai',
  baB='{r} prima dello styling – appartamento a Dubai',
  topic='{t} – consiglio di interior design di Farnaz Sadeghian',
  reel='{t} – reel di arredamento di Decor with Farnaz',
  book='Soul of the Room, libro di interior design di Farnaz Sadeghian'),
'zh': dict(
  metaTitle='迪拜室内设计师与软装设计 · Farnaz Sadeghian | Third Skin Interiors',
  metaDesc='迪拜认证室内软装设计师 Farnaz Sadeghian：室内设计咨询、3D 效果图设计以及公寓和别墅软装，社交平台 39 万粉丝。',
  metaKeywords='迪拜室内设计, 迪拜室内设计师, 迪拜软装设计, 公寓装修设计, 别墅室内设计, 3D 室内设计, Farnaz Sadeghian',
  altHeroImg='Farnaz Sadeghian，迪拜认证室内软装设计师',
  wallart='沙发上方的装饰画照片墙 – 家居软装灵感',
  corner='布置好的客厅角落，配单人椅和台灯',
  bathroom='暖色中性调的浴室室内设计',
  colour='宁静客厅的配色灵感',
  pillar='迪拜开放式公寓中经过装饰的柱子',
  console='玄关边桌与装饰摆件布置',
  accessories='家居摆件搭配：花瓶、书籍与蜡烛',
  baA='{r}改造后 – Farnaz Sadeghian 软装设计，迪拜公寓',
  baB='{r}改造前 – 迪拜公寓',
  topic='{t} – Farnaz Sadeghian 室内设计建议',
  reel='{t} – Decor with Farnaz 家居软装短视频',
  book='Farnaz Sadeghian 的室内设计书《Soul of the Room》'),
'ja': dict(
  metaTitle='ドバイのインテリアデザイナー · Farnaz Sadeghian | Third Skin Interiors',
  metaDesc='ドバイの認定インテリアデコレーター Farnaz Sadeghian。インテリアデザイン相談、3D デザイン、アパートやヴィラのスタイリングを提供（フォロワー 39 万人）。',
  metaKeywords='ドバイ インテリアデザイン, ドバイ インテリアデザイナー, インテリアコーディネート, 3D インテリアデザイン, ヴィラ インテリア, Farnaz Sadeghian',
  altHeroImg='ドバイの認定インテリアデコレーター Farnaz Sadeghian',
  wallart='ソファ上のフレームアートのギャラリーウォール – インテリアのアイデア',
  corner='アームチェアとランプでスタイリングしたリビングのコーナー',
  bathroom='温かみのあるニュートラルカラーのバスルームデザイン',
  colour='落ち着いたリビングのための配色アイデア',
  pillar='ドバイのオープンプランのアパートで装飾した柱',
  console='小物でスタイリングした玄関のコンソール',
  accessories='インテリア小物のスタイリング：花瓶、本、キャンドル',
  baA='{r}のスタイリング後 – Farnaz Sadeghian、ドバイのアパート',
  baB='{r}のスタイリング前 – ドバイのアパート',
  topic='{t} – Farnaz Sadeghian のインテリアのヒント',
  reel='{t} – Decor with Farnaz のインテリアリール',
  book='Farnaz Sadeghian のインテリアデザイン本『Soul of the Room』'),
'de': dict(
  metaTitle='Innenarchitektin & Interior Designerin in Dubai · Farnaz Sadeghian | Third Skin Interiors',
  metaDesc='Zertifizierte Raumgestalterin in Dubai. Interior-Design-Beratung, 3D-Raumplanung und Styling für Wohnungen und Villen von Farnaz Sadeghian (390K Follower).',
  metaKeywords='Interior Designer Dubai, Innenarchitektin Dubai, Raumgestaltung Dubai, Interior Design Beratung, 3D Raumplanung, Wohnung einrichten Dubai, Farnaz Sadeghian',
  altHeroImg='Farnaz Sadeghian, zertifizierte Raumgestalterin in Dubai',
  wallart='Galeriewand mit gerahmten Bildern über dem Sofa – Deko-Idee',
  corner='Gestylte Wohnzimmerecke mit Sessel und Lampe',
  bathroom='Badgestaltung in warmen, neutralen Tönen',
  colour='Farbpaletten-Idee für ein ruhiges Wohnzimmer',
  pillar='Dekorierte Säule in einer offenen Wohnung in Dubai',
  console='Konsole im Eingangsbereich mit Deko-Accessoires',
  accessories='Accessoires stylen: Vasen, Bücher und Kerzen',
  baA='{r} nach dem Styling von Farnaz Sadeghian – Wohnung in Dubai',
  baB='{r} vor dem Styling – Wohnung in Dubai',
  topic='{t} – Einrichtungstipp von Farnaz Sadeghian',
  reel='{t} – Deko-Reel von Decor with Farnaz',
  book='Soul of the Room, Interior-Design-Buch von Farnaz Sadeghian'),
'fr': dict(
  metaTitle='Décoratrice & architecte d’intérieur à Dubaï · Farnaz Sadeghian | Third Skin Interiors',
  metaDesc='Décoratrice d’intérieur certifiée à Dubaï. Conseil en décoration, conception 3D et home styling d’appartements et de villas, par Farnaz Sadeghian (390K abonnés).',
  metaKeywords='décoratrice d’intérieur Dubaï, architecte d’intérieur Dubaï, décoration intérieure Dubaï, conseil déco, conception 3D intérieur, home staging Dubaï, Farnaz Sadeghian',
  altHeroImg='Farnaz Sadeghian, décoratrice d’intérieur certifiée à Dubaï',
  wallart='Mur de cadres au-dessus du canapé – idée déco',
  corner='Coin salon décoré avec fauteuil et lampe',
  bathroom='Décoration de salle de bain aux tons neutres et chaleureux',
  colour='Idée de palette de couleurs pour un salon apaisant',
  pillar='Colonne décorée dans un appartement ouvert à Dubaï',
  console='Console d’entrée décorée d’accessoires',
  accessories='Mise en scène d’accessoires : vases, livres et bougies',
  baA='{r} après la décoration de Farnaz Sadeghian – appartement à Dubaï',
  baB='{r} avant la décoration – appartement à Dubaï',
  topic='{t} – conseil déco de Farnaz Sadeghian',
  reel='{t} – reel déco de Decor with Farnaz',
  book='Soul of the Room, livre de décoration de Farnaz Sadeghian'),
}

FEED = ['wallart', 'corner', 'bathroom', 'colour', 'pillar', 'console', 'accessories']
ROOMS = {'living': 'baLiving', 'bedroom': 'baBedroom', 'kitchen': 'baKitchen', 'dining': 'baDining', 'entry': 'baEntry', 'kids': 'baKids'}

def block(I18N):
    out = []
    import re
    strip = lambda s: re.sub(r'<[^>]+>', '', s)
    for l in LANGS:
        d = T[l]; g = lambda k: strip(I18N[l].get(k) or I18N['en'][k])
        o = {k: d[k] for k in ('metaTitle', 'metaDesc', 'metaKeywords', 'altHeroImg')}
        o['altBook'] = d['book']
        for f in FEED: o['altF_' + f] = d[f]
        for room, key in ROOMS.items():
            o['altBaA_' + room] = d['baA'].replace('{r}', g(key)); o['altBaB_' + room] = d['baB'].replace('{r}', g(key))
        for i in range(1, 9): o[f'altT{i}'] = d['topic'].replace('{t}', g(f't{i}'))
        for i in range(1, 4): o[f'altR{i}'] = d['reel'].replace('{t}', g(f'reel{i}'))
        out.append(f'Object.assign(I18N.{l}, {json.dumps(o, ensure_ascii=False)});')
    return '\n'.join(out)
